### PR TITLE
Add support for Django 2.2

### LINKED ISSUE #4: Django 2.2 support
Running the tests illustrates the error perfectly:

```python
ERROR: test_multi_hop (tests.tests.RelationshipTests)

Traceback (most recent call last):
  File "/Users/oskar/git/django-relativity/tests/tests.py", line 302, in test_multi_hop
    self.assertSeqEqual(cart_items, CartItem.objects.filter(product__filters=f))
  File "/Users/oskar/git/django-relativity/tests/tests.py", line 21, in assertSeqEqual
    self.assertSequenceEqual(list(seq1), list(seq2))
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1087, in execute_sql
    sql, params = self.as_sql()
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 488, in as_sql
    from_, f_params = self.get_from_clause()
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 760, in get_from_clause
    clause_sql, clause_params = self.compile(from_clause)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/datastructures.py", line 86, in as_sql
    extra_sql, extra_params = compiler.compile(extra_cond)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 405, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/oskar/git/django-relativity/relativity/fields.py", line 71, in as_sql
    query=lookup_query, allow_joins=True, reuse=compiler.query.used_aliases
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/query_utils.py", line 93, in resolve_expression
    clause, joins = query._add_q(self, reuse, allow_joins=allow_joins, split_subq=False)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1202, in build_filter
    value = self.resolve_lookup_value(value, can_reuse, allow_joins, simple_col)
  File "/Users/oskar/.pyenv/versions/3.6.7/envs/dj-rel/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1025, in resolve_lookup_value
    value = value.resolve_expression(self, **kwargs)
TypeError: resolve_expression() got an unexpected keyword argument 'simple_col'
```

### PR DESCRIPTION
**Pull request by OskarPersson**
Fixes #4

### CODE REVIEW

**Comment by OskarPersson** [comment]
Most of the tests does pass after my changes. @AlexHill do you have any ideas on how to solve the rest? Django 3 is soon here but I will try to look into that as soon as this is merged.

**Comment by OskarPersson** [comment]
I think the error is because of `from_fields` being empty (https://github.com/OskarPersson/django-relativity/blob/django-22/relativity/fields.py#L308) but I'm not sure what it could be set to instead

**Comment by AlexHill** [comment]
Hi Oskar,

Thanks for submitting this - I’ll have a look soon as I can. Obviously
relativity relies heavily on undocumented Django internals, so I hope we
can make it work with whatever ORM changes have landed in 2.2/3.0...

Alex

**Comment by OskarPersson** [comment]
@AlexHill Have you had anytime to look into this? Otherwise I'm thinking of giving it another go soon

**Comment by AlexHill** [comment]
Hi @OskarPersson. It looks like we can resolve these by returning an empty dict for _known_related_objects in fields.py, line 104. I'm not sure what the implications of this are though - do you have any idea? I assume it might mean some things are re-fetched that shouldn't be?

**Comment by AlexHill** [comment]
Declining in favour of #6. Thanks for the report and investigation!

**Pull request closed without merging**
