### PR TITLE
Use `only_private=True` when contributing to class to exclude Relationships from migrations

### PR DESCRIPTION
**Pull request by AlexHill**

### CODE REVIEW

**Comment by LincolnPuzey** [comment]
Does this mean the Relation fields are totally ignored from Migrations?

Could you then remove the backported compat code for making migrations work? And the note in the README about migrations?

**Comment by AlexHill** [comment]
Yeah, it means they won't appear in migrations which is ideal.

But it also has some other effects on how `Relationship` behaves in inherited classes, which I want to at least define with some tests before merging.

**Comment by AlexHill** [comment]
To answer the actual question, yes! The compat code should be able to be removed.

**Comment by AlexHill** [comment]
Added some tests around exclude including some broken behaviour. Still need to resolve the issue of using `Relationship` in an abstract base class, or document that it doesn't work yet.

**Comment by OskarPersson** [comment]
How can I best help here? I would really like to get rid of the migrations

**Comment by AlexHill** [comment]
Me too. I've made a change to master to make some test models inherit from abstract parents, and rebased this branch on top of it. A lot of the tests will now fail on this branch - we need to get them passing before this can be merged.

Feel free to have a crack! It's to do with how `model` is set on the field when it's inherited...internally some Querysets are producing the base class when they should be producing the child class, or the other way around - it's been a while.

**Comment by OskarPersson** [comment]
@AlexHill Will take a look when/if I get time

**Comment by AlexHill** [comment]
Got on a roll and did a bit of digging. 0.2.0 now released migration-free!

**Comment by OskarPersson** [comment]
🎉

**Pull request merged**
